# Generated by Django 6.0.4 on 2026-04-18 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True, unique=True)),
                ('status_code', models.IntegerField(choices=[('2', 'success'), ('1', 'crawling'), ('3', 'failed'), ('0', 'pending')], default=0)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='seo.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='seo.page')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('h1', models.JSONField(default=list)),
                ('h2', models.JSONField(default=list)),
                ('h3', models.JSONField(default=list)),
                ('p_count', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('internal_links', models.IntegerField(default=0)),
                ('external_links', models.IntegerField(default=0)),
                ('keywords', models.JSONField(default=list)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='seo_insight_title_52d793_idx'), models.Index(fields=['image_count'], name='seo_insight_image_c_4a280b_idx'), models.Index(fields=['internal_links'], name='seo_insight_interna_2f011b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['domain'], name='seo_page_domain__db1f02_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['status_code'], name='seo_page_status__8148a7_idx'),
        ),
    ]
